Copyright year. Cosmetic.

diff --git a/debugpanel b/debugpanel
--- a/debugpanel
+++ b/debugpanel
@@ -1,3 +1,17 @@
 #!/bin/sh
 
-python2 $(dirname $(realpath $0))/$(basename $0).py "$@"
+if which realpath ; then
+  REALPATH=realpath
+elif which grealpath ; then
+  REALPATH=grealpath
+else
+  echo "Core command line utility realpath (or grealpath) not found" >&2
+  exit 1
+fi
+if which python2 ; then
+  PYTHON2=python2
+else
+  echo "Python 2 executable (or symbolic link) python2 not found" >&2
+  exit 1
+fi
+$PYTHON2 $(dirname $($REALPATH $0))/$(basename $0).py "$@"
